### ISSUE TITLE
GPUhack November: SASmodels sample

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1064]
Make it work

**Comment by willend** [comment]
(will require rewrite of tool that cuts functions from SASmodels code-base)

**Comment by climbcat** [comment]
We have looked into this sample component, and we have concluded that the current mechanism for getting the parameters into the component using the initializer notation {v1, v2, ..}, does not work. This is due to the "vector" keyword in cogen3 being broken! 

#### What does not work: 

In the component parameters struct:
<pre>
...
MCNUM *model_pars;
---
</pre>
in e.g. _sample_setpos, which is run before the INITIALIZE block function:
<pre>
...
_sample_var._parameters.model_pars[3] = (double []){ 1.0 , 7.0 , 40.0 , 400.0 , 60.0 , 60.0 };
---
</pre>

#### How it could be done:

In the component parameters struct:
<pre>
...
MCNUM model_pars[6}; // <- the number of values in the vector, counted by the cogen
---
</pre>
in e.g. _sample_setpos, which is run before the INITIALIZE block function:
<pre>
...
  _sample_var._parameters.model_pars[0] = 1.0;
  _sample_var._parameters.model_pars[1] = 7.0;
  _sample_var._parameters.model_pars[2] = 40.0;
  _sample_var._parameters.model_pars[3] = 400.0;
  _sample_var._parameters.model_pars[4] = 60.0;
  _sample_var._parameters.model_pars[5] = 60.0;
---
</pre>

**Comment by willend** [comment]
Interesting, may be related to the issues found with PowderN and Isotropic_Sqw that both use a vector type!

**Comment by willend** [comment]
Looking at the new debugging-output from PowderN (https://github.com/McStasMcXtrace/McCode/commit/fa4b24a2182f86d31e5a7911c0373397ceff16d6) in Test_PowderN_concentric, one gets e.g.

```
column 0 is 17
column 1 is 1
column 2 is 0
column 3 is 0
column 4 is 0
column 5 is 0
column 6 is 0
column 7 is 0
column 8 is 0
PowderN: Pow0: Concentric mode - remember to include the 'opposite' copy of this component !
WARNING  The equivalent, 'opposite' comp should have concentric=0
Opening input file '/u/data/pkwi/McStas/mcstas/3.0-dev/tools/Python/mcrun/../mccodelib/../../../data/Fe.laz' (Table_Read_Offset)
Table from file 'Fe.laz' (block 1) is 17 x 18 (x=1:5), constant step. interpolation: linear
  '# TITLE *Iron-Fe-[IM3-M] Swanson, H.E.;Tatge, E.[1954] [Iron alpha phase];# ...'
PowderN: Pow0: Reading 17 rows from Fe.laz
PowderN: Pow0: Read 17 reflections from file 'Fe.laz'
PowderN: Pow0: Vc=24.04 [Angs] sigma_abs=5.12 [barn] sigma_inc=0.8 [barn] reflections=Fe.laz
column 0 is 0
column 1 is 0
column 2 is 0
column 3 is 0
column 4 is 0
column 5 is 0
column 6 is 0
column 7 is 0
column 8 is 0
Opening input file '/u/data/pkwi/McStas/mcstas/3.0-dev/tools/Python/mcrun/../mccodelib/../../../data/Fe.laz' (Table_Read_Offset)
Table from file 'Fe.laz' (block 1) is 17 x 18 (x=1:5), constant step. interpolation: linear
  '# TITLE *Iron-Fe-[IM3-M] Swanson, H.E.;Tatge, E.[1954] [Iron alpha phase];# ...'
PowderN: Pow: Reading 17 rows from Fe.laz
PowderN: Pow: Read 17 reflections from file 'Fe.laz'
PowderN: Pow: Vc=24.04 [Angs] sigma_abs=5.12 [barn] sigma_inc=0.8 [barn] reflections=Fe.laz
column 0 is 1
column 1 is 0
column 2 is 0
column 3 is 0
column 4 is 0
column 5 is 24
column 6 is 0
column 7 is 5
column 8 is 0
```
