### ISSUE TITLE
McStas 3.0 / 2.7 on macOS Big Sur, mcgui crashing when opening instrument files 

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1101]
On macOS 11 Big Sur, mcgui may crash when attempting to save instruments to specific folders.

It looks like this is connected to specific File / Folder / Disk access permissions on macOS. There are indications that a cure could be to allow "Full Disk Access" to mcgui, see the relevant System Preferences pane.

**Comment by mortensales** [comment]
The fix for this is to grant bin/bash Full Disk Access.
(I can't say if there are any security implications by doing this, so be careful).
This is done by going to:
System Preferences > Security and Privacy > Privacy > Full Disk Access
And then use the + sign to add. 
(Use shift+command+period to show hidden files)
Go to Macintosh HD (or whatever your drive is called), then to bin, then select bash to add it.
