### ISSUE TITLE
Issue after replacing mccodelib/pqtgfrontend.py (macOS Monterey 12.6.1, Apple M1 Pro chip)

### ISSUE THREAD

**Issue by XuShuqi7** [McStasMcXtrace/McCode#1325]
Hi Everyone,

after following the guidelines on the website of McStas, I still have problems related to the plot. I would like to ask for help, thank you! The error message is put as followed:

```
loading system configuration
mcplot error: module 'mccodelib.pqtgfrontend' has no attribute 'print_help'
Traceback (most recent call last):
  File "/Applications/McStas-3.1.app/Contents/Resources/mcstas/3.1/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 67, in <module>
    main(args)
  File "/Applications/McStas-3.1.app/Contents/Resources/mcstas/3.1/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 57, in main
    raise e
  File "/Applications/McStas-3.1.app/Contents/Resources/mcstas/3.1/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 50, in main
    pqtgfrontend.print_help(nogui=True)
AttributeError: module 'mccodelib.pqtgfrontend' has no attribute 'print_help'
```

Best regards,
Shuqi

**Comment by willend** [comment]
Hello @XuShuqi7,

I am afraid what happened is that the link on the front page of mcstas.org points to the "always newest" version of pqtgfrontend.py and not a specific revision. - Since then we have had a Hackathon leading up to the next releases, which has meant a lot of restructuring in some of the python tools....

[This link](https://raw.githubusercontent.com/McStasMcXtrace/McCode/54c348b02fb20c6182866edd8ecd10096f7c25db/tools/Python/mccodelib/pqtgfrontend.py) should take you to a version that is corrected wrt. the original problem and remains compatible with the rest of the code in McStas 3.1.

Hope this helps - and sorry for the inconvenience!

You may also simply try using the matplotlib-based plotter with 3.1 - while awaiting the 3.2 release which will come before Christmas.

**Comment by XuShuqi7** [comment]
Hi @willend,

thank you very much for your prompt reply! The issue is resolved. I am looking forward to the new 3.2 release.

Best regards,
Shuqi

**Comment by willend** [comment]
I am reopening for documentation purposes, but marking "ready for release" :)
