### ISSUE TITLE
McStas 3.4: pol_tabled field segfaults with a large table (~2M points)

### ISSUE THREAD

**Issue by sq-meng** [McStasMcXtrace/McCode#1532]
I eventually tracked the problem to interpolation-lib trying to allocate a large array on stack:
The code in question is in interpolation-lib.c, line 383:
https://github.com/McStasMcXtrace/McCode/blob/9deb3f82aebd103a5b79f9c554147e7b26148cc3/common/lib/share/interpolation-lib.c#L381C22-L388C45
Changing the allocation to:
`double* vector = (double*) calloc(sizeof(double), table.rows)` fixed the problem for me. Is there any particular reason that it is allocated on stack? My C is very rusty (not a reference to the Rust language) so I'm not sure if it would cause other problems.

**Comment by willend** [comment]
@sq-meng thanks for reporting the issue and the proposed change. 

I don't myself immediately see a reason to not use a `calloc()` as you propose, but maybe @farhi or @ebknudsen have a point of view?

Otherwise I am very willing to implement the change and run the test suite to investigate if there are unwanted side-effects.

**Comment by willend** [comment]
@sq-meng the change has now been implemented on our "main" repo, meaning that it is in place for next official 3.x release.

And the output of the nightly test-suite looks normal https://new-nightly.mcstas.org/2023-12-08/overview.html
