### ISSUE TITLE
Error in materials using Absortion_sample

### ISSUE THREAD

**Issue by vribgar** [McStasMcXtrace/McCode#1534]
I have made an "instrument file" where the components are: a source (Source_flat), the sample (Absorption_sample) which are two concentric cylinders of different materials, a base support (Arm) where a transmission grid (Grating_trans) is placed and finally a detector (PSD_monitor). 

When I try to change the materials of de cylinders, for example, H2O in the outer cylinder and Pb in the inner one, I get exactly the same results as when I put Glass in the inner cylinder and Al in the outer. The same happens when I try any combination of materials. I don't know what's wrong because when I run the simulation it seems to read the correct material files.

<img width="418" alt="Test_6_con_rejilla" src="https://github.com/McStasMcXtrace/McCode/assets/150797747/dbd8c423-b538-4455-985b-8aa06b421ca4">
<img width="418" alt="Test_6_vidrio_Pb_rejilla" src="https://github.com/McStasMcXtrace/McCode/assets/150797747/2c3b63d8-7a08-46e5-aec4-ddfe79fb2b75">

Thanks!

**Comment by willend** [comment]
@vribgar thanks for creating the issue! Absorption_sample sounds like we are talking McXtrace here?

Please provide
* Information on version of the McStas/McXtrace code used
* Information on OS and version
* e.g. a .zip file including your instrumentfile, any needed other bits like local components or datafiles
* An output dataset or input parameters needed to reproduce the issue

**Comment by farhi** [comment]
You may try the Fluorescence sample, which uses XRayLib as an alternative. It does not require to prepare data files, and only needs a chemical formula.

**Comment by vribgar** [comment]
> @vribgar thanks for creating the issue! Absorption_sample sounds like we are talking McXtrace here?
> 
> Please provide
> 
> * Information on version of the McStas/McXtrace code used
> * Information on OS and version
> * e.g. a .zip file including your instrumentfile, any needed other bits like local components or datafiles
> * An output dataset or input parameters needed to reproduce the issue


Version of the McXtrace: 3.2
OS: Windows 11
Here are the instrument file (Test_6.instr) and the results file (psd_giant.dat) 
[Test_6_results.zip](https://github.com/McStasMcXtrace/McCode/files/13672610/Test_6_results.zip)

Thank you!

**Comment by willend** [comment]
@vribgar, just had an evening session together with @farhi and we believe we identified the issue:

In the chosen geometry, your signal will be dominated by the direct (non-attenuated) beam - which is why your intensity does not change much.

We propose to put a circular slit to only look at the attenuated signal, find an example attached derived from Test_Absorption. instr.

I also attach output from the final monitor in material combinations of C in O and Cu in C.

<img width="1372" alt="Screenshot 2023-12-19 at 20 12 38" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/bee6c7c2-c3ec-4a0a-8a7b-67e32eaeae41">
<img width="1263" alt="Screenshot 2023-12-19 at 20 12 10" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/effc680a-44b8-4146-94ab-30a6136fa5a6">

[Test_Absorption.instr.txt](https://github.com/McStasMcXtrace/McCode/files/13719495/Test_Absorption.instr.txt)

(Or do as you would at an actual experiment: "data reduction", i.e. subtract / normalise by the "empty" beam)

**Comment by vribgar** [comment]
Hi, it was very helpful. We have managed to get the simulation to work and have obtained the expected results. But now we would like to resize the components parameters to simulate larger objects and we have a question: why for such small samples as the example you have provided (Test_Absorption) the distances between the components are so large? (3m between thr source and the sample)

We also have the doubt if this program (McXtrace) can simulate at that scale (sample size 20 -50 cm) or is it only for smaller scales? 

I attach the code in .txt extension as I cannot upload the .zip with the .instr file and the results because they take too much space (>30 MB).
[Test_6_Slit_Grating.txt](https://github.com/McStasMcXtrace/McCode/files/13727827/Test_6_Slit_Grating.txt)
<img width="960" alt="Test_6_slit_rejilla_2" src="https://github.com/McStasMcXtrace/McCode/assets/150797747/f055a1af-99d9-4b9d-a209-4e39b7363c97">
, thank you very much for your attention!

**Comment by willend** [comment]
@vribgar the reason that e.g. material sizes are mostly small and distances long in the provided examples is that many of the examples relate to synchrotron X-ray beam lines. :-) 

Nothing should however prevent that you use McXtrace in other settings, there are for instance people in the astronomy domain that use McXtrace. :-)

**Comment by vribgar** [comment]
Thank you so much!!! :)
