### ISSUE TITLE
McXtrace: Single_crystal component simulation bug

### ISSUE THREAD

**Issue by minghuisvn** [McStasMcXtrace/McCode#1634]
A bug occurred when simulating the diffraction of a single crystal  Si in McXtrace3.2. The code is as follows:
```
DEFINE INSTRUMENT SimpleInstrument(E0=8.02)
TRACE
COMPONENT Origin = Progress_bar()
AT (0, 0, 0) ABSOLUTE

COMPONENT Source = Source_flat(
    yheight = 1e-3, xwidth = 1e-3, dist = 1, focus_xw = 1e-3,
    focus_yh = 1e-3, E0 = E0, dE = 0.1)
AT (0, 0, 0) RELATIVE Origin

COMPONENT Sample = Single_crystal(xwidth=0.01, yheight=0.01, zdepth=0.01,
delta_d_d=1e-4, mosaic = 5,
ax = 5.44, ay = 0, az = 0,
bx = 0, by = 5.44, bz = 0,
cx = 0, cy = 0, cz = 5.44,
reflections="Si.lau", order=1)
AT (0, 0, 1) RELATIVE Source

COMPONENT beamstop = Beamstop(radius=5e-3)
AT (0, 0, 0.1-1e-3) RELATIVE PREVIOUS

COMPONENT Detector = PSD_monitor(
    nx=200, ny=200, xwidth=0.5, yheight=0.5, filename="psd0",restore_xray=0
)
AT (0, 0, 1e-3) RELATIVE PREVIOUS

END
```
The simulation result is:
![image](https://github.com/McStasMcXtrace/McCode/assets/68952982/e8d0a7fa-1b9f-456a-a42f-44d563954504)
Nothing could be found in the figure of the psd monitor, that is the monitor did not received scattered x-ray photons. However, when i trace that process, and found the x-ray particles actually hit the psd monitor as shown below:
![image](https://github.com/McStasMcXtrace/McCode/assets/68952982/8f54a60e-8d5d-4462-b29c-ad58d904d53b)
The results are contradictory.

**Comment by willend** [comment]
Dear @minghuisvn,

First a little general advice:
* Please do not immediately assume that there is a **bug** every time you see a simulation result you don't understand. McXtrace may seem "simple to use" and "should work", but rest assured that it will simulate exactly what you ask it - including things that can not work. :-)
* Please have a look in the `examples` folder for inspiration wrt. parametrisation, there is for instance an `SX_instrument.instr` 
* Always think carefully if you have yourself parametrised something that could be "unphysical" 
* Perhaps try making your way through some of our "School" material in the Schools repo - e.g. https://github.com/McStasMcXtrace/Schools/tree/master/2023/SOLEIL_May_2023 - this should give you a better basis for running McXtrace :-)

Now, let us try to understand what could be happening in your simulation.
1. For every incoming x-ray, the Single_crystal algorithm will lay out reciprocal space in the form of the Ewald construction to investigate if there are reflections that may scatter for this incoming ray. In this case they are actually present as you will see, but not in the forward direction where your detector is located. 
2. It turns out that in the forward direction, the only "output channel" is in fact incoherent scattering which by default has a cross-section of 0, meaning scattered rays of weight 0 - which will never show up as intensity in your detector. :-) (If you look closely, the PSD is in fact measuring ~ 200k events out of 1e6, but all with 0 intensity...)
3. Your incoming beam is a "pink beam", perhaps start from a Laue-geometry and a white beam
4. The sample crystallography is perhaps not oriented as you initially thought, adding a sample rotation might work
5. Making use of PSD_monitor_4PI allows you to get an overview of all scattered rays, this also helps... 

In the attached, many of the above points have been added to your instrument, which seems to help. :) 

I also attach screenshots of the default output on linear / log scale - there is scattering... 
![Screenshot 2024-07-04 at 10 44 59](https://github.com/McStasMcXtrace/McCode/assets/8593355/a8e517c5-0f5f-4630-9698-c96d1a50763b)
![Screenshot 2024-07-04 at 10 44 52](https://github.com/McStasMcXtrace/McCode/assets/8593355/e9662b23-e3f7-4bb2-b288-cbe012268f77)



Best,
Peter
P.s.: Be aware that I am starting vacation this Friday, so I may not respond to further questions/enquiries for a while :-) But perhaps you will be in luck that @farhi has time to look.


[SX_instrument.instr.txt](https://github.com/user-attachments/files/16095916/SX_instrument.instr.txt)

**Comment by minghuisvn** [comment]
Dear @willend,

Thank you for your advice!
I am sorry about my hasty question without careful consideration.  Thanks for you advice! I understand that the results that may be confusing at first glance could be understood through the careful analysis on a basis of physical knowledge (May be i should spend more time on that).I will dig into examples and annual school materials again. 
Thanks for your patient explanation and instructions!

Best regards,
Sun

**Comment by willend** [comment]
Dear @minghuisvn,

You are very welcome and good luck practicing McXtrace. :-) 

Best,
Peter

**Comment by minghuisvn** [comment]
@willend I encountered a problem that a reasonable diffraction spots could not be produced when i simulated the Al single crystal diffraction using a monochromatic light (E0=100). Is there any setting mistakes in my instrument file? The results are:
![image](https://github.com/user-attachments/assets/7306eba5-67d8-4c3f-9bc1-029f1acfd56d)
I attached the .ins and .hkl files used. The hkl file is obtained using "cif2hkl -l 0.124 -x -o Al.hkl Al.cif" command, and cif file is downloaded form ICSD dataset (ICSD code is 53774).
And another problem is how can i set the crystal coordinate to align with the sample coordinate. Now i set "ax=0, ay=4.046, az=0, bx=0, by=0, bz=4.046, cx=4.046, cy=0,  cz=0", when i set the "ax=4.046, ay=0, az=0, bx=0, by=4.046, bz=0, cx=0, cy=0,  cz=4.046", the lattice orientation in direct and reciprocal space contains nan value, as follows:
![image](https://github.com/user-attachments/assets/f2a221fd-f725-4d90-abdf-8f627ed0dc4a)
[Al_diffraction.instr.txt](https://github.com/user-attachments/files/16244759/Al_diffraction.instr.txt)
[Al.hkl.txt](https://github.com/user-attachments/files/16244755/Al.hkl.txt)

**Comment by farhi** [comment]
Hi @minghuisvn 
I guess the lambda>0.12 Angs is not low enough to cope with a 100 keV X-ray beam. So the reachable Bragg spots in the Al.txt file are limiting the scattering range.

For the crystal orientation, the nan results probably from a division by 0 in the computation of the cell volume V0. I'm pushing in the source code a test leading to a stop when V0 is NULL/nan. But in your case, it seems to be a wrong value in the `cx` parameter. Please check your `c` vector definition.

**Comment by minghuisvn** [comment]
@farhi Thanks for your responses! I decreased the lambda to 0.06 Angs for cif2hkl command, however records in PSD remained unchanged (irregular spots in image center region). Could you give me some hints about this phenomenon?
And I still don't understand why my c vector setting is wrong. Could you explain more details about mistakes?

**Comment by willend** [comment]
@minghuisvn did you figure out yourself in the end or do you need more help? :) 

(Sorry, have been / am very busy elsewhere.)

**Comment by minghuisvn** [comment]
@willend Thanks for your responses! I compiled and installed the cif2hkl tool software in WSL subsystem of windows platform, and downloaded the cif file from cod dataset in which  the cif file does not contain apostrophes for atom positions, e.g., 55 'z, -y+1/2' for cif file from ICSD datasets, x+1/2' .  As a result, the diffraction angles in PSD detectors looks reasonable.
