### ISSUE TITLE
McStas Comps: Single_crystal error in barns logic

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#290]
There is an error reported by Mads Bertelsen in the input logic of Single_crystal wrt to the barns parameter. The use of the parameter is not consistent which may lead to values of sigma_abs and sigma_inv that are a factor 100 off.

**Comment by willend** [comment]
@ebknudsen will you have time for this one before release?

**Comment by willend** [comment]
I had a look - there are two places where we have check for <pre> if (barns) </pre> in the code.

1) Around line 1093 - which I think should <b>not</b> be there - since 
 a) Our datafiles all indicate e.g. sigma_abs [barns]
 b) The component docs indicate that the sigma_inc and sigma_abs are indeed in barns
<pre>
   if (barns) { 
      /*If cross sections are given in barns, we need a scaling factor of 100 
        to get scattering lengths in m, since V0 is assumed to be in AA*/
      abs_xlen *= 100; inc_xlen *= 100; 
    }
</pre>

2) Around line 1194 where we are looking at data from the .laz/.lau datafile, which can indeed be with either barns or fm^2 units:
<pre>
      if (barns) {
        coh_xlen *= 100; tot_xlen *= 100;
      } /* else assume fm^2 */
</pre>

I propose we skip the first check and simply always apply the factor of 100.

@ebknudsen what do you think?

**Comment by ebknudsen** [comment]
I agree with the proposed logic (i.e. sigma_inc & sigma_abs always in barns) and have the switch apply only to what comes from the lau/laz-file.
Arguably we could get rid of abs_xlen because it's not being used.

**Comment by willend** [comment]
OK - I will submit a commit that uses this new proposed logic. Shouldn't we use abs_xlen for something?

**Comment by willend** [comment]
Anyway, closing since the reported bug is now gone
