### ISSUE TITLE
Using Save As adds lots of extra lines in 2.4

### ISSUE THREAD

**Issue by jfkcooper** [McStasMcXtrace/McCode#448]
I am using windows 10, and mcstas 2.4. I am editing an instrument from within McStas, but when I save As the instrument, I have extra lines created between every line in my code.

**Comment by mducle** [comment]
It's a windows CR/LF problem. The file is read in binary mode and then converted to text mode (supposedly to fix a MacOS bug) but this leaves the `\r\n` line endings. However, then python converts `\n` to `\r\n` again in `file.write()` on Windows by default, giving doubled lines. 

The fix is to change line `f = open(str(instr), 'w')` in `tools/Python/mccodelib/utils.py` in the function `save_instrfile()` (currently in line 615: https://github.com/McStasMcXtrace/McCode/blob/master/tools/Python/mccodelib/utils.py#L615 ) to  `f = open(str(instr), 'w', newline='\n')`

**Comment by willend** [comment]
Thanks @mducle, confirmed to work
