### ISSUE TITLE
Any further Union updates?

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#466]
@mads-bertelsen McStas 2.4 will now ship within days - this is just a heads-up for you...

**Comment by mads-bertelsen** [comment]
@willend Wish I had the time to go through all the headers and create some better example instruments, but I have to focus on finishing that thesis. 
I was considering if it would be possible to move the dedicated Union include files (Union_initialization.c, Geometry_functions.c, Union_functions.c) to the contrib/union folder so that it would be easier to send out a new version of Union components without risking mismatch between those and the components?

**Comment by willend** [comment]
@mads-bertelsen fair enough, first things first. 👍 :-)

Don't worry about the .c snippets, we'll simply bump a "complete" mcstas-comps in a few months (which is something we ought to do anyway).

**Comment by willend** [comment]
@mads-bertelsen let's simply close it here then - except if you could put the MACS instr in of course?

**Comment by mads-bertelsen** [comment]
@willend I would like to submit the MACS model, but there are a few issues. The major problem was that it used older versions of the Union components, but I am working on it at the moment, and just had it updated to the newest verison. It does however use a lot of small components with small tweaks/include c files, which I don't quite know how should be handled?

**Comment by willend** [comment]
@mads-bertelsen no worries, we never promised anyone it would be in this release. :-) Again, if we progress in the next few months we can bump a fresh mcstas-comps where it can be included.
