### ISSUE TITLE
cif2hkl on Mac OS needs updated rpath and headermax_stufff....

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#668]
- otherwise may try to pick up libgfortran from wrong location..

**Comment by farhi** [comment]
I have solved this by adding the required library into the iFit repo. 

It consists in:

- add libgfortran lib https://github.com/McStasMcXtrace/iFit/blob/5d4a68c9596bb55feca21bd7bc0862f748c73196/Scripts/Models/Factory/private/libgfortran.3.dylib
- add libquadmath https://github.com/McStasMcXtrace/iFit/blob/5d4a68c9596bb55feca21bd7bc0862f748c73196/Scripts/Models/Factory/private/libquadmath.0.dylib
- setting `DYLD_LIBRARY_PATH=.` for execution

this is rather complex still for a normal user. In iFit the execution is wrapped into the Matlab function, so that the definition of the path can be prepended in the system command. Commit is https://github.com/McStasMcXtrace/iFit/commit/5d4a68c9596bb55feca21bd7bc0862f748c73196

Did not succeed in compiling static on MacOSX yet, but this would solve the issue as well.

**Comment by willend** [comment]
Well, DYLD_LIBRARY_PATH is not really supported anymore...

I just looked, and what I use in other places (and just checked it works on a user's macOS High Sierra)
1) (Re)compile with miniconda-provided gfortran and -headerpad_max_install_names
2) install_name_tool $MCSTAS/miniconda3/lib /path/to/cif2hkl

**Comment by willend** [comment]
But indeed a static binary would probably be nicer...

**Comment by willend** [comment]
I will experiment with this later
https://stackoverflow.com/questions/17590525/correct-way-to-statically-link-in-gfortran-libraries-on-osx

**Comment by willend** [comment]
Yup, this works:

<pre>
mcstas-2.4.1 env ~ $ which cif2hkl
/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/cif2hkl
mcstas-2.4.1 env ~ $ otool -L /Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/cif2hkl
/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/cif2hkl:
	/usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	/usr/local/lib/gcc/7/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/gcc/lib/gcc/7/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
mcstas-2.4.1 env ~ $ cd /Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/libs/cif2hkl/
mcstas-2.4.1 env cif2hkl $ gfortran -c cif2hkl.F90 -o cif2hkl.o   
mcstas-2.4.1 env cif2hkl $ ld -o /Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/cif2hkl -no_compact_unwind -arch x86_64 -macosx_version_min 10.12.0 -lSystem /Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/miniconda3/lib/libgfortran.a /Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/miniconda3/lib/libquadmath.a /Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/miniconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/libgcc.a cif2hkl.o 
mcstas-2.4.1 env cif2hkl $ otool -L /Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/cif2hkl
/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/cif2hkl:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
mcstas-2.4.1 env cif2hkl $ 
</pre>

**Comment by farhi** [comment]
Excellent, I will try that as well for the MacOSX executables shipped with iFit.

**Comment by willend** [comment]
You're welcome. :-) Have annotated the "recipe" above a little more to be easier on the eyes.

**Comment by willend** [comment]
Looks to be a real pain to add this within CMake, propose to simply do the minor steps as a postfix to the McStas macOS build within the ./build_macos_mcstas script)

**Comment by willend** [comment]
Done with a hack through build_macos_mcstas - a better way would be to build everything via condo
