### ISSUE TITLE
If mcrun --info fails, mcgui remains silent about error messages

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#684]
Example: On a fresh macOS that doesn't happen to have the headers in place in /usr/include

We should use same mechanism for all calls to externals from mcgui and forward stdout / stderr

**Comment by climbcat** [comment]
There is a kind for fix for this now: the 'mcrun --info' thread now forwards all stdout to the screen. Due to some difficulties a while back, we had to forward stderr to stdout, in order to get real-time updates from the process: 
<code
            process = subprocess.Popen(self.cmd, 
                                       stdout=subprocess.PIPE,
                                       stderr=subprocess.STDOUT,
                                       stdin=subprocess.PIPE, ...)
</code>
Therefore we have to print literally everything the process tells us. 

In addition to this, we are back to the undesired behavior of mcrun itself. The compilation error will not be propagated, but only a python stack trace error finally stating "process returned with 1".

**Comment by climbcat** [comment]
This: a55cf97e2ea57a6a0f191dc5538fefddc5e1aac4

**Comment by willend** [comment]
I believe what is now in place looks good, with the side effect that all of the "junk" from --info is of course present in the terminal window. :-)

**Comment by willend** [comment]
DONE
