### ISSUE TITLE
Prepare for a richer v2.0 "test" system

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#752]
Existing mcrun.pl --test evaluates single, numerical output which results in a text-based "abstract" of the test:

<pre>
Test Abstract for selftest_luGz
...
[notest] RTP_DIF (no test procedure)
[OK]     Test_MCPL_output_1 (accuracy, 1 %)
[??????] Test_Jump_Iterate_5 (reference not found)
[FAILED] ILL_D4_6 (accuracy off by 740 %)
[OK]     Test_Pol_Set_7 (accuracy, 0 %)
[FAILED] linup-5_8 (accuracy off by 26 %)
[notest] h8_test_legacy (no test procedure)
[OK]     ISIS_test_9 (accuracy, 1 %)
...
# # Execution check:    FAILED. 3 instrument(s) did not compile/execute.
# >> Check instruments and mcstas installation.
# End Date: Mon Jan 28 21:43:52 2019{quote}
</pre>
Implement an improved system that can be used to compare two test runs, including graphical output, i.e. a richer test "report".

For an example see attached PDF
[McCode test system v. 2.0.pdf]
(https://github.com/McStasMcXtrace/McCode/files/2875543/McCode.test.system.v.2.0.pdf)

**Comment by climbcat** [comment]
I've gotten a fair bit with a mctest python script, that may be used instead of mcrun.pl --test. However, it doesn't really the the same as the mcrun.pl --test does.

### mctest.py:

This script requires a version number, if none is given it goes through all installed versions, e.g. subfolders of "mcstas root" (defaults to /urs/share/mcstas) with an "environment" file in them. It searches for instrument files, copies them into a folder tree in "test root". Then it compiles and runs, and records the results and compile/run time into a datastructure that is saved to disk. Stdout/stderr of every compile and simulation is saved to disk, only a summary and meta information is printed to the terminal.

- results are stored on disk and can be parsed/read/browsed/served/analyzed/diffed later on, potentially with a different tool
- can be set to test all installed versions every night, if combined with a build system
- separately tests compile and run
- can test a specific version
- sets environment variables in Python before running mcrun

A lot of tweaking and testing is still required, here are a few of the thing that need doing:

- test output monitor values up against target values and report
- user input or confit for mcstas_root and test_root
- option to test "system default" mcstas version

**Comment by climbcat** [comment]
The tool has been updated somewhat. 

More features:
- ncount
- seed

**Comment by willend** [comment]
I believe we can safely close this ticket. What we have in place for the mcstas-3.0 branch already running with daily tests at http://new-nightly.mccode.org is sufficient.
