### ISSUE TITLE
A possibly stupid question about writing a batch script

### ISSUE THREAD

**Issue by jfkcooper** [McStasMcXtrace/McCode#813]
I am trying to write a script to feed into mcstas-shell (v 2.5) which contains a loop, e.g.:

int(i) for(i=0;i<4;i=i+1){
    mcrun my_instrument.instr -n 1e5 scan_param=(5.0*i)
    }
This gives an "Invalid value '(5.0*i)' for floating point parameter scan_param (mcparamerror_double)" error
I have tried casting i to a float but have had no success, though I will be the first to admit I'm no expert.
I was wondering 

1. what language should this script be programmed in? I'm currently calling it my_script.bat which the shell seems happy,  as long as I don't actually use the iterable.

2. Am I doing this the wrong way round in some way?

(3. Is there a better way I should be asking for help other than a github issue)

**Comment by ebknudsen** [comment]
Question 1: That depends on what you like - preferrably no language at all  at all :-) See below:
Question 2: Slightly - yes. Again see below
(Question 3: A question like this is perhaps better handled on the mailing list, since it is a question and not an issue as such. But that's just my opinion.)

Solutions to the actual problem:
The easiest way is to do this with mcrun itself by:
```mcrun my_instrument.instr scan_parameter=0,3 -N 4``` 
which will do a point scan using the values 0,1,2,3

If you really want to use the shell for some reason
1. In the DOS command prompt:
```
FOR %P in (0,1,3) DO mcrun my_instrument.instr scan_parameter=%P
```
.. but you might want do read what ```FOR /?``` tells you. my DOS-prompt skills are admittedly rusty.

2. In a bash shell:
```bash
for lam in `seq 1.0 0.1 4.0`;
do
    mcrun my_instrument.instr scan_parameter=$lam
done
```
... for details on seq - you should check the man page

3. alternate bash version :
```bash
sequence="1.0 1.1 1.2 4.5 7.2"  
for scan_parameter in sequence;  
do
    mcrun my_instrument.instr scan_parameter=$lam
done  
```

**Comment by jfkcooper** [comment]
Many thanks for the response. My aim had been to do nested loops to explore a large parameter space, and I couldn't work out a good way of making mcrun do this, hence the question. (I will also try the mailing list next time). Thanks
Jos

**Comment by ebknudsen** [comment]
Oh - Now I see what you intend to do. Then I should perhaps add a few extra comments about mcrun.
1. You can do co-linear scans:
```mcrun my_instrument.instr -N11 parA=0,1 parB=0,2```
which would at the same time scan parA and parB in 11 steps.
2. There's the option of doing a grid scan:
```mcrun --multi my_instrument.instr -N5 parA=0,1 parB=0,2```  
This would scan parA btw. 0,1 in 5 steps for 5 values of B btw 0,2. Note that the scan points would be numbered consecutively in the same way as for a single line scan, i.e. 0,1,...,24. This also extends to more than 2 parameters: ```parA=0,1 parB=0,2 parC=100,200``` etc.
3. ...or a list scan 
```mcrun --list my_instrument.instr -N5 parA=0,1,2,3 parB=0,2, 24,86```
which would run a simulation at pts.: (parA,parB)={ (0,0), (1,2), (2,24), (3,86) }.
Again the scan points would be put in the output directory in a single sequence.

From the GUI you can do 1) but to use 2) and 3) you have to call mcrun from the command line.
It is of course possible to do the same thing in the shell with nested loops if you prefer that.
