### ISSUE TITLE
mcdoc (python) may mix up outputs in generated html

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#831]
As can be seen in the attached, sometimes the generated html output from mcdoc stems from another component

![Screenshot 2019-07-16 at 10 20 08](https://user-images.githubusercontent.com/8593355/61298765-185ffc00-a7df-11e9-919f-24ffb8239bd5.png)

(Shape.html from Shape.comp got the content of Guide_chaneled.comp)

**Comment by climbcat** [comment]
Currently, mcdoc is parsing components in the wrong directory due to a mccode-config issue (possibly local), it fails parsing certain files, it is too verbose, and I can not reproduce the error on my system. 

It seems that incorrect content was written to the file shape.html at installation time. One theory is that this is a side effect of a parsing issue. If we address the robustness of the parsing, and combine with a valid "null-result" for faulty parses, the issue may disappear.

**Comment by climbcat** [comment]
Possibly fixed on other systems by 485d419171500e11e9eb5a4be59f4981c5d1645a, can not reproduce locally.

**Comment by willend** [comment]
Must have been a one-off, can no longer reproduce it here, neither with distributed 2.5 mcdoc or current main version
