### ISSUE TITLE
McXtrace: polycrystal: the Table_Rebin call uses all the available memory

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#840]
In component [samples/Polycrystal]( https://github.com/McStasMcXtrace/McCode/blob/master/mcxtrace-comps/samples/Polycrystal.comp), the call to `Table_Rebin` around line 878:
- Table_Rebin(&(AbsorbtionInfo->Table));

can eat-up all the available memory. Probably that the step_x is small in the given data files, which then results in a **very large allocation** (e.g. 32 Gb). 

**Temporary fix**: This is avoided by using a 'small' ncount, e.g. 1e6. Larger values will trigger the if statement to be true, and call Table_Rebin. Perhaps Table_Rebin should be given a maximum allocation/vector length to limit its memory footprint.

**Comment by ebknudsen** [comment]
I've thought about a slightly more low key solution. The reason to use the rebin function at all was to ensure constant step tables since they will  be used a lot. In which case replacing the data  tables with already rebinned versions could do the trick.
Their raison d'etre is to mainly to handle the more complex absorption cross section that we have for X-rays, and avoiding rebinning is something that many comps will benefit from.

**Comment by ebknudsen** [comment]
I have now set a limit in read_table-lib, such the Table_Rebin will not rebin to more than 1 M rows.
Do you think that is too limiting @farhi ? Not sure how much it is used elsewhere.

**Comment by ebknudsen** [comment]
just another detail - this doesn't do anything else than skip the rebinning process if the requested number of rows becomes excessive. One could think of generating a new step_x (minimal step) and (re)interpolate the table accordingly.

**Comment by farhi** [comment]
I think this issue is solved with commit https://github.com/McStasMcXtrace/McCode/commit/713e257567ee62d8305cbb236ede913acded0741
