### ISSUE TITLE
cif2hkl: Propagate fixes present in iFit to McCode.

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#899]
cif2hkl in iFit may  have a newer version of crysFML that fixes some of the X-ray issues.. This should be propagated to the McCode repo as well.

**Comment by farhi** [comment]
There seem to be no formal difference between our iFit and McCode versions. 

However, there have been updates since then at the CrysFML source code repo:
- https://code.ill.fr/scientific-software/crysfml
- I downloaded it so that we have a local copy here: [CFML_src.zip](https://github.com/McStasMcXtrace/McCode/files/3922657/CFML_src.zip)

So it may make sense to update cif2hkl and rebuild it.

**Comment by willend** [comment]
@ebknudsen I believe we did this?

**Comment by farhi** [comment]
I think we checked that the 2 versions are the same.

**Comment by ebknudsen** [comment]
Ok so there appears to be a bunch of small edits to crysFML that have propagated into McCode cif2hkl. I suppose that cif2hkl was constructed by concatenating the relevant bits of crysFML into one file and adding an extra driver, right? 
@farhi Did you automate that? 
Maybe it makes more sense these days to add crysFML as a submodule (it is a git repo now) like we do for mcpl, and use it as a "real" library for cif2hkl. Or is that overcomplicating matters?

**Comment by farhi** [comment]
Yes, it can be done like that. The compilation order was a little touchy, as some modules depend on others. In order to solve this, I chose to concatenate the used bits into a single source code. It can certainly be done differently by sleceting the modules in order. I think Juan has made regular  improvements, that will then benefit to cif2hkl.

**Comment by ebknudsen** [comment]
As you say: The biggest advantage of a submodule construction, I think, is that this way we get Juan's updates directly with no extra effort needed. These days with Juan using both git and cmake should be sufficiently aligned with our own process, that it _should_ be relatively easy.
I'll give it a try I think.

**Comment by farhi** [comment]
The command to compile cif2hkl with separate modules from crysFML is:
```bash
gfortran -O2 CFML_GlobalDeps_Linux.f90 CFML_Math_Gen.f90 CFML_String_Util_gf.f90 CFML_Math_3D.f90 CFML_Sym_Table.f90 CFML_Chem_Scatt.f90 CFML_Symmetry.f90 CFML_Cryst_Types.f90 CFML_Reflct_Util.f90 CFML_Atom_Mod.f90 CFML_Geom_Calc.f90 CFML_Molecules.f90 CFML_Form_CIF.f90 CFML_Sfac.f90 -o cif2hkl cif2hkl.F90 -lm
```
The crysFML code is available at:
- https://code.ill.fr/scientific-software/crysfml

**Comment by farhi** [comment]
I just created a repo for cif2hkl:
- https://github.com/farhi/cif2hkl

Currently uses latest CrysFML as separate modules [May the 4th, 2020 ;-) ] and a Makefile.
Release 1.2 has older (iFit) code as single source code.

Did not use submodule, as CrysFML is **very** large but we only use _some_ modules in its 'Src' directory at https://code.ill.fr/scientific-software/crysfml/tree/master/Src

**Comment by ebknudsen** [comment]
That's excellent! My thoughts exactly - I experimented with it yesterday and came to more or less the same conclusion. I did find one thing though - The F^2 factors returned by CrysFML do not change with wavelength, so there's some kind of normalization that gets dropped somewhere.

**Comment by farhi** [comment]
close with previous commit
