### ISSUE TITLE
GPUhack: Cathegorize remaining non-compiling instruments

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#918]

**Comment by farhi** [comment]
Here is a short status on non compiling instruments. Those in **bold** seem to be possibly solved rather easily.

28/01/2020 20:35:33 

Not compiling: examples
--------------------------------
- **BTsimple**
- ESS_butterfly_Guide_curved_test
- ESS_butterfly_test
- ESS_butterfly_tfocus_NOFOCUS_test
- ESS_butterfly_tfocus_test
- ESS_Testbeamline_HZB_V20
- **ILL_H15_IN6**
- **ILL_IN6**
- **ISIS_CRISP** -gsl
- templateLaueGPU ** openCL remove ?

Not compiling: examples-fail:
--------------------------------------
- **Reflectometer**
- Test_Scatter_log_ssw_mcnp
- **Test_StatisticalChopper**

Not compiling: example-parked:
------------------------------------------
- **ILL_H5_new** order of comp ref for GETPAR
- **RITA-II**
- SE_example2
- SEMSANS_instrument
- Test_Fermi
- Test_Guides_Curved
- Test_Magnetic_Constant
- Test_Magnetic_Majorana
- Test_Magnetic_Rotation
- Test_Magnetic_Userdefined
- Test_Pol_Bender
- Test_Pol_Bender_Vs_Guide_Curved
- Test_Scatter_log_losses
- Test_Scatter_log_mvalues
- Test_shellguides

Now compile: example-fail:
-----------------------------
These can be put back into examples.
- ILL_BRISP
- ILL_H53_IN14
- Test_Monitor_Sqw
- templateTOF
- Test_Pol_TripleAxis

**Comment by farhi** [comment]
Lots of improvements here. Most 'non-magnetic' and 'non-ESS  source' instruments compile now.
**ILL_IN6** remains, and has its own ticket #938 
Many instruments were move into the main-stream 'examples' directory. Some components were fixed in this respect.

Not compiling: #944 ESS_butterfly
------------------
- ESS_butterfly_Guide_curved_test
- ESS_butterfly_test
- ESS_butterfly_tfocus_NOFOCUS_test
- ESS_butterfly_tfocus_test
- ESS_Testbeamline_HZB_V20

Not compiling: polarisation is using pointers
-------------------
- SE_example2
- SEMSANS_instrument
- Test_Magnetic_Constant
- Test_Magnetic_Majorana
- Test_Magnetic_Rotation
- Test_Magnetic_Userdefined
- Test_Pol_Bender
- Test_Pol_Bender_Vs_Guide_Curved

Not compiling: scatter_logger is using pointers / MCNP lib
--------------------
- Test_Scatter_log_losses
- Test_Scatter_log_mvalues
- Test_Scatter_log_ssw_mcnp

Not compiling: but can probably be OK after limited work
----------------
- Test_shellguides: may require some extensive edits as the Guide_shell is complex.
- Test_Fermi: can be made OK if we agree to get rid of the Vitess Fermi chopper (low)
- Test_Guides_Curved: can be made OK if we get rid of the Polarisated guide, which uses pointers

**Comment by willend** [comment]
Superseded by  https://github.com/McStasMcXtrace/McCode/issues/1055. Closing
