### ISSUE TITLE
GPUhack: Monitors, with priority

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#947]
From http://gpuhack.mccode.org/remaining_comps_20200127.txt
### High priority
* DivLambda_monitor.comp
* DivPos_monitor.comp
* Monitor_Sqw.comp
* Res_monitor.comp
* PSDcyl_monitor.comp
* TOFSANSdet.comp
### Low priority
- TOFlog_monitor.comp
- Monitor_4PI.comp
- PSD_monitor_psf.comp
- PSD_monitor_psf_eff.comp
- Radial_div.comp
- Monitor_Optimizer.comp
- PSDlin_diff_monitor.comp

**Comment by willend** [comment]
Most of these should also be done, review for final status

**Comment by ebknudsen** [comment]
I've done a bit of digging in Monitor_Sqw. This does not work with the new (as of 466b2f68781334af28b5c823adaca3fbfbaa580e) implementation of USERVARS.
The reason is that Vars.UserVariables123 are now strings that may be used to choose a thread variable (aka uservar) attached to the neutron - this clashes with the usage in Monitor_Sqw (lines 256+) where they are used as doubles. For this to work, the component needs a real uservar. I can think of some options:
1. we introduce the  USERVAR  sections in comps as well. These should likely also be protected by prefixing the component instance name to avoid clashes
2. We require that the user declares in the instrument file a uservar, and sets a parameter to Monitor_Sqw which tells which variables are to be used - this would also require a cogen'd "set" function to set a user variable from inside trace, but that's easy.
3. Same as 2 but we define a few generic uservar-fields on every particle that may be used for these kind of things across the board. Obviously this can only be used within single components as there is no guarantee that another component might not use the variable for something else.
The second option renders Monitor_Sqw somewhat pointless as it would now be very close to the operation of a regular Monitor_nD
